/*
 * clouddb
 *
 * Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
 *
 * API version: 2018-07-02T10:10:19Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package clouddb

type CommonCode struct {
	Code *string `json:"code,omitempty"`

	CodeName *string `json:"codeName,omitempty"`
}
