/*
 * clouddb
 *
 * Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
 *
 * API version: 2018-07-02T10:10:19Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package clouddb

type Zone struct {

	// 존(Zone)번호
	ZoneNo *string `json:"zoneNo,omitempty"`

	// 존(Zone)명
	ZoneName *string `json:"zoneName,omitempty"`

	// 존(Zone)설명
	ZoneDescription *string `json:"zoneDescription,omitempty"`
}
