/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type ClusterInputBody struct {

	// 클러스터 이름
	Name *string `json:"name"`

	// 클러스터 타입
	ClusterType *string `json:"clusterType"`

	// 쿠버네티스 버전 [Version 조회 API](/docs/compute-vpckubernetesservice-nksv2#k8sSupportedVersion)
	K8sVersion *string `json:"k8sVersion,omitempty"`

	// 로그인 키 이름
	LoginKeyName *string `json:"loginKeyName"`

	// Zone 코드
	ZoneCode *string `json:"zoneCode,omitempty"`

	// Zone 번호
	ZoneNo *int32 `json:"zoneNo,omitempty"`

	// Hypervisor Code
	HypervisorCode *string `json:"hypervisorCode,omitempty"`

	// Region의 코드
	RegionCode *string `json:"regionCode"`

	// Public network
	PublicNetwork *bool `json:"publicNetwork,omitempty"`

	// CNI Plugin Code (ncloud-vpc-cni or cilium)
	KubeNetworkPlugin *string `json:"kubeNetworkPlugin,omitempty"`

	// [VPC 번호](/docs/networking-vpc-vpcmanagement-getvpclist)
	VpcNo *int32 `json:"vpcNo"`

	// [서브넷 번호 목록](/docs/networking-vpc-subnetmanagement-getsubnetlist)
	SubnetNoList []*int32 `json:"subnetNoList"`

	// [로드밸런서 전용 Private Subnet 번호](/docs/networking-vpc-subnetmanagement-getsubnetlist)
	SubnetLbNo *int32 `json:"subnetLbNo,omitempty"`

	// [로드밸런서 전용 Private Subnet 번호](/docs/networking-vpc-subnetmanagement-getsubnetlist)
	LbPrivateSubnetNo *int32 `json:"lbPrivateSubnetNo,omitempty"`

	// [로드밸런서 전용 Public Subnet 번호](/docs/networking-vpc-subnetmanagement-getsubnetlist)
	LbPublicSubnetNo *int32 `json:"lbPublicSubnetNo,omitempty"`

	//
	Log *ClusterLogInput `json:"log,omitempty"`

	KmsKeyTag *string `json:"kmsKeyTag,omitempty"`

	// 클러스터 인증 타입
	AuthType *string `json:"authType,omitempty"`

	// 클러스터 생성 시 bootstrap access entry 자동 생성 여부
	BootstrapAccessEntry *bool `json:"bootstrapAccessEntry,omitempty"`

	//
	DefaultNodePool *DefaultNodePoolParam `json:"defaultNodePool,omitempty"`

	// 추가 노드풀
	NodePool []*NodePoolDto `json:"nodePool,omitempty"`
}
