/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type IpAclsDto struct {
	DefaultAction *string `json:"defaultAction"`

	Entries []*IpAclsEntriesDto `json:"entries,omitempty"`
}
