/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type NodePoolTaint struct {
	Key *string `json:"key"`

	Value *string `json:"value,omitempty"`

	Effect *string `json:"effect"`
}
