/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type SubnetDto struct {

	// 추가할 서브넷 ID<ul><li>[getSubnetList](/docs/networking-vpc-subnetmanagement-getsubnetlist) 액션을 통해 확인</li></ul>
	Number *int32 `json:"number"`
}
