/*
 * vnks
 *
 * <br/>https://nks.beta-apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type UpdateNodepoolSubnetDto struct {
	Subnets []*int32 `json:"subnets"`
}
