/*
 * cdn
 *
 * <br/>https://ncloud.apigw.ntruss.com/cdn/v2
 *
 * API version: 2018-07-04T02:02:10Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cdn

type CommonCode struct {
	Code *string `json:"code,omitempty"`

	CodeName *string `json:"codeName,omitempty"`
}
