/*
 * vloadbalancer
 *
 * VPC Load Balancer 관련 API<br/>https://ncloud.apigw.ntruss.com/vloadbalancer/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancer

type LoadBalancerRuleCondition struct {

	// 룰조건유형
RuleConditionType *CommonCode `json:"ruleConditionType,omitempty"`

	// 호스트헤더조건
HostHeaderCondition *HostHeaderCondition `json:"hostHeaderCondition,omitempty"`

	// 경로패턴조건
PathPatternCondition *PathPatternCondition `json:"pathPatternCondition,omitempty"`
}
