/*
 * vloadbalancer
 *
 * VPC Load Balancer 관련 API<br/>https://ncloud.apigw.ntruss.com/vloadbalancer/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancer

type RemoveLoadBalancerListenerCertificateRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// 로드밸런서리스너번호
LoadBalancerListenerNo *string `json:"loadBalancerListenerNo"`

	// SSL인증서번호
SslCertificateNo *string `json:"sslCertificateNo,omitempty"`
}
