/*
 * vloadbalancer
 *
 * VPC Load Balancer 관련 API<br/>https://ncloud.apigw.ntruss.com/vloadbalancer/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancer

type Target struct {

	// 타겟번호
TargetNo *string `json:"targetNo,omitempty"`

	// 헬스체크상태
HealthCheckStatus *CommonCode `json:"healthCheckStatus,omitempty"`

	// 헬스체크응답
HealthCheckResponse *string `json:"healthCheckResponse,omitempty"`
}
