/*
 * vredis
 *
 * <br/>https://ncloud.apigw.ntruss.com/vredis/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vredis

// ACG번호리스트
type AccessControlGroupNo struct {
	AccessControlGroupNo int32 `json:"accessControlGroupNo,omitempty"`
}
