/*
 * vredis
 *
 * <br/>https://ncloud.apigw.ntruss.com/vredis/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vredis

type CloudRedisBackupDetailList struct {

	// CloudRedis백업상세리스트
CloudRedisBackupDetailList []*CloudRedisBackupDetail `json:"cloudRedisBackupDetailList,omitempty"`
}
