/*
 * vredis
 *
 * <br/>https://ncloud.apigw.ntruss.com/vredis/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vredis

type DeleteCloudRedisInstanceResponse struct {
	RequestId *string `json:"requestId,omitempty"`

	ReturnCode *string `json:"returnCode,omitempty"`

	ReturnMessage *string `json:"returnMessage,omitempty"`

	TotalRows *int32 `json:"totalRows,omitempty"`

	// CloudRedis인스턴스리스트
	CloudRedisInstanceList []*CloudRedisInstance `json:"cloudRedisInstanceList,omitempty"`
}
