/*
 * vredis
 *
 * <br/>https://ncloud.apigw.ntruss.com/vredis/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vredis

type DeleteCloudRedisConfigGroupRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// configGroup번호
ConfigGroupNo *string `json:"configGroupNo,omitempty"`
}
