/*
 * vhadoop
 *
 * <br/>https://ncloud.apigw.ntruss.com/vhadoop/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vhadoop

type CloudHadoopAddOnList struct {

	// CloudHadoopAdd-On리스트
CloudHadoopAddOnList []*CloudHadoopAddOn `json:"cloudHadoopAddOnList,omitempty"`
}
