/*
 * vhadoop
 *
 * <br/>https://ncloud.apigw.ntruss.com/vhadoop/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vhadoop

type CloudHadoopLoginKey struct {

	// CloudHadoop인증키이름
KeyName *string `json:"keyName,omitempty"`
}
