/*
 * vhadoop
 *
 * <br/>https://ncloud.apigw.ntruss.com/vhadoop/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vhadoop

type CloudHadoopInstanceList struct {

	// CloudHadoop인스턴스리스트
CloudHadoopInstanceList []*CloudHadoopInstance `json:"cloudHadoopInstanceList,omitempty"`
}
