/*
 * vhadoop
 *
 * <br/>https://ncloud.apigw.ntruss.com/vhadoop/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vhadoop

type GetCloudHadoopAddOnListRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// Cloud Hadoop 이미지 상품 코드
CloudHadoopImageProductCode *string `json:"cloudHadoopImageProductCode,omitempty"`
}
