/*
 * vhadoop
 *
 * <br/>https://ncloud.apigw.ntruss.com/vhadoop/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vhadoop

type GetCloudHadoopInstanceListRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// ZONE코드
ZoneCode *string `json:"zoneCode,omitempty"`

	// VPC번호
VpcNo *string `json:"vpcNo,omitempty"`

	// Subnet번호
SubnetNo *string `json:"subnetNo,omitempty"`

	// CloudHadoop클러스터이름
CloudHadoopClusterName *string `json:"cloudHadoopClusterName,omitempty"`

	// CloudHadoop인스턴스번호리스트
CloudHadoopInstanceNoList []*string `json:"cloudHadoopInstanceNoList,omitempty"`

	// CloudHadoop서버이름
CloudHadoopServerName *string `json:"cloudHadoopServerName,omitempty"`

	// CloudHadoop서버인스턴스번호리스트
CloudHadoopServerInstanceNoList []*string `json:"cloudHadoopServerInstanceNoList,omitempty"`

	// 페이지번호
PageNo *int32 `json:"pageNo,omitempty"`

	// 페이지사이즈
PageSize *int32 `json:"pageSize,omitempty"`
}
