/*
 * vsourcedeploy
 *
 * <br/>https://vpcsourcedeploy.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcedeploy

type GetStageListResponse struct {

Project *GetIdNameResponse `json:"project,omitempty"`

StageList []*GetIdNameResponse `json:"stageList,omitempty"`
}
