/*
 * vsourcedeploy
 *
 * <br/>https://vpcsourcedeploy.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcedeploy

type GetDeployHistoryDetailResponseConfig struct {

Strategy *string `json:"strategy,omitempty"`

File *GetDeployHistoryDetailResponseFile `json:"file,omitempty"`

Targets []*GetDeployHistoryDetailResponseTargets `json:"targets,omitempty"`
}
