/*
 * vsourcedeploy
 *
 * <br/>https://vpcsourcedeploy.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcedeploy

type GetStageDetailResponse struct {

Project *GetIdNameResponse `json:"project,omitempty"`

Id *int32 `json:"id,omitempty"`

Name *string `json:"name,omitempty"`

Type_ *string `json:"type,omitempty"`

Config *GetStageDetailResponseConfig `json:"config,omitempty"`
}
