/*
 * vsourcedeploy
 *
 * <br/>https://vpcsourcedeploy.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcedeploy

type ScenarioConfigCmdPrePost struct {

User *string `json:"user,omitempty"`

Cmd *string `json:"cmd,omitempty"`
}
