/*
 * vsourcedeploy
 *
 * <br/>https://vpcsourcedeploy.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcedeploy

type ScenarioConfigCanaryConfigMetrics struct {

Name *string `json:"name,omitempty"`

SuccessCriteria *string `json:"successCriteria,omitempty"`

QueryType *string `json:"queryType,omitempty"`

Weight *int32 `json:"weight,omitempty"`

Metric *string `json:"metric,omitempty"`

Filter *string `json:"filter,omitempty"`

Query *string `json:"query,omitempty"`
}
