/*
 * vsourcedeploy
 *
 * <br/>https://vpcsourcedeploy.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcedeploy

type ScenarioConfigLoadBalancer struct {

LoadBalancerTargetGroupNo *int32 `json:"loadBalancerTargetGroupNo,omitempty"`

DeleteServer *bool `json:"deleteServer,omitempty"`
}
