/*
 * vsourcedeploy
 *
 * <br/>https://vpcsourcedeploy.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcedeploy

type ScenarioConfigCanaryConfig struct {

CanaryCount *int32 `json:"canaryCount,omitempty"`

AnalysisType *string `json:"analysisType,omitempty"`

Timeout *int32 `json:"timeout,omitempty"`

Prometheus *string `json:"prometheus,omitempty"`

Env *ScenarioConfigCanaryConfigEnv `json:"env,omitempty"`

Metrics []*ScenarioConfigCanaryConfigMetrics `json:"metrics,omitempty"`

AnalysisConfig *ScenarioConfigCanaryConfigAnalysisConfig `json:"analysisConfig,omitempty"`

PassScore *int32 `json:"passScore,omitempty"`
}
