/*
 * vsourcedeploy
 *
 * <br/>https://vpcsourcedeploy.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcedeploy

type ScenarioConfigFileObjectStorage struct {

Bucket *string `json:"bucket,omitempty"`

Object *string `json:"object,omitempty"`
}
