/*
 * vmssql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmssql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmssql

type CloudMssqlServerInstance struct {

	// Cloud DB for MSSQL 서버 인스턴스 번호 
CloudMssqlServerInstanceNo *string `json:"cloudMssqlServerInstanceNo,omitempty"`

	// Cloud DB for MSSQL 서버 이름 
CloudMssqlServerName *string `json:"cloudMssqlServerName,omitempty"`

	// Cloud DB for MSSQL 서버 역할 
CloudMssqlServerRole *CommonCode `json:"cloudMssqlServerRole,omitempty"`

	// Cloud DB for MSSQL 서버 인스턴스 상태 이름 
CloudMssqlServerInstanceStatusName *string `json:"cloudMssqlServerInstanceStatusName,omitempty"`

	// Cloud DB for MSSQL 서버 인스턴스 상태 
CloudMssqlServerInstanceStatus *CommonCode `json:"cloudMssqlServerInstanceStatus,omitempty"`

	// Cloud DB for MSSQL 서버 인스턴스 OP 
CloudMssqlServerInstanceOperation *CommonCode `json:"cloudMssqlServerInstanceOperation,omitempty"`

	// 리전 코드 
RegionCode *string `json:"regionCode,omitempty"`

	// ZONE 코드
ZoneCode *string `json:"zoneCode,omitempty"`

	// VPC 번호
VpcNo *string `json:"vpcNo,omitempty"`

	// Subnet 번호
SubnetNo *string `json:"subnetNo,omitempty"`

	// 데이터 스토리지 사이즈
DataStorageSize *int64 `json:"dataStorageSize,omitempty"`

	// CPU 개수
CpuCount *int32 `json:"cpuCount,omitempty"`

	// 메모리 사이즈
MemorySize *int64 `json:"memorySize,omitempty"`

	// Public Subnet 여부
IsPublicSubnet *bool `json:"isPublicSubnet,omitempty"`

	// Cloud DB for MSSQL 상품 코드
CloudMssqlProductCode *string `json:"cloudMssqlProductCode,omitempty"`

	// 사설 도메인명
PrivateDomain *string `json:"privateDomain,omitempty"`

	// 공인 도메인명
PublicDomain *string `json:"publicDomain,omitempty"`

	// 생성일자
CreateDate *string `json:"createDate,omitempty"`

	// 구동시간
Uptime *string `json:"uptime,omitempty"`

	// 데이터 스토리지 타입
DataStorageType *CommonCode `json:"dataStorageType,omitempty"`

	// 사용중인 데이터 스토리지 사이
UsedDataStorageSize *int64 `json:"usedDataStorageSize,omitempty"`
}
