/*
 * vmssql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmssql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmssql

type CloudMssqlBackup struct {

	// Cloud DB for Mssql 인스턴스 번호
CloudMssqlInstanceNo *string `json:"cloudMssqlInstanceNo,omitempty"`

	// Cloud DB for Mssql 서비스 이름
CloudMssqlServiceName *string `json:"cloudMssqlServiceName,omitempty"`

	// 백업 파일 보관 기간 
BackupFileRetentionPeriod *int32 `json:"backupFileRetentionPeriod,omitempty"`

	// FullBackup 시작 시간 
BackupTime *string `json:"backupTime,omitempty"`

	// 보관중인 Backup 데이터 사이즈 
TotalBackupDataSize *int64 `json:"totalBackupDataSize,omitempty"`

	// FullBackup 데이터 사이즈 
FullBackupDataSize *int64 `json:"fullBackupDataSize,omitempty"`

	// Log Backup 데이터 사이즈 
LogBackupDataSize *int64 `json:"logBackupDataSize,omitempty"`

	// Log Backup 수 
LogBackupCount *int32 `json:"logBackupCount,omitempty"`
}
