/*
 * vmssql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmssql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmssql

type CommonCode struct {

	// 코드
Code *string `json:"code,omitempty"`

	// 코드명
CodeName *string `json:"codeName,omitempty"`
}
