/*
 * vmssql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmssql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmssql

type DmsFile struct {

	// 파일길이
FileLength *int64 `json:"fileLength,omitempty"`

	// 파일작성시간
LastWriteTime *string `json:"lastWriteTime,omitempty"`

	// 파일이름
FileName *string `json:"fileName,omitempty"`
}
