/*
 * vmssql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmssql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmssql

type GetCloudMssqlBackupListRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// 페이지 번호
PageNo *int32 `json:"pageNo,omitempty"`

	// 페이지 사이즈
PageSize *int32 `json:"pageSize,omitempty"`
}
