/*
 * vmssql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmssql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmssql

type GetDmsOperationRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// 요청번호
RequestNo *string `json:"requestNo"`
}
