/*
 * vmssql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmssql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmssql

type RestoreDmsDatabaseRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// CloudMssql인스턴스번호
CloudMssqlInstanceNo *string `json:"cloudMssqlInstanceNo"`

	// 파일이름
FileName *string `json:"fileName"`

	// recovery 모드 여부
IsRecovery *bool `json:"isRecovery"`

	// 새로운 데이터베이스 이름
NewDatabaseName *string `json:"newDatabaseName"`
}
