/*
 * vmssql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmssql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmssql

type SetDmsObjectStorageInfoRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// access key
ObjectStorageAccessKey *string `json:"objectStorageAccessKey"`

	// secret key
ObjectStorageSecretKey *string `json:"objectStorageSecretKey"`

	// endpoint
Endpoint *string `json:"endpoint"`

	// 버킷 이름
BucketName *string `json:"bucketName"`
}
