/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v2)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses2

type ClusterNode struct {
	ComputeInstanceName string `json:"computeInstanceName,omitempty"`
	ComputeInstanceNo   int    `json:"computeInstanceNo,omitempty"`
	PrivateIp           string `json:"privateIp,omitempty"`
	ServerStatus        string `json:"serverStatus,omitempty"`
	NodeType            string `json:"nodeType,omitempty"`
	Subnet              string `json:"subnet,omitempty"`
}
