/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v2)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses2

type GetSearchEngineClusterInfoListResponse struct {
	AllowedClusters    []AllowedSearchEngineClusterInfo    `json:"allowedClusters,omitempty"`
	CurrentPage        int                                 `json:"currentPage,omitempty"`
	DisallowedClusters []DisallowedSearchEngineClusterInfo `json:"disallowedClusters,omitempty"`
	IsFirst            bool                                `json:"isFirst,omitempty"`
	IsLast             bool                                `json:"isLast,omitempty"`
	PageSize           int32                               `json:"pageSize,omitempty"`
	TotalCount         int64                               `json:"totalCount,omitempty"`
	TotalPage          int32                               `json:"totalPage,omitempty"`
}
