/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v2)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses2

type OpenApiOsProductVo struct {
	InfraResourceTypeCode string `json:"infraResourceTypeCode,omitempty"`
	ProductCode           string `json:"productCode,omitempty"`
	ProductEnglishDesc    string `json:"productEnglishDesc,omitempty"`
	ProductName           string `json:"productName,omitempty"`
	ProductType2Code      string `json:"productType2Code,omitempty"`
	SoftwareTypeCode      string `json:"softwareTypeCode,omitempty"`
}
