/*
 * autoscaling
 *
 * <br/>https://ncloud.apigw.ntruss.com/autoscaling/v2
 *
 * API version: 2018-06-21T02:22:22Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package autoscaling

type DeleteAutoScalingLaunchConfigurationRequest struct {

	// 론치설정명
	LaunchConfigurationName *string `json:"launchConfigurationName"`
}
