/*
 * vautoscaling
 *
 * VPC Auto Scaling 관련 API<br/>https://ncloud.apigw.ntruss.com/vautoscaling/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vautoscaling

type GetLaunchConfigurationListRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// 론치설정번호리스트
LaunchConfigurationNoList []*string `json:"launchConfigurationNoList,omitempty"`

	// 론치설정이름리스트
LaunchConfigurationNameList []*string `json:"launchConfigurationNameList,omitempty"`

	// 페이지번호
PageNo *int32 `json:"pageNo,omitempty"`

	// 페이지사이즈
PageSize *int32 `json:"pageSize,omitempty"`

	// 정렬리스트
SortList []*Sort `json:"sortList,omitempty"`
}
