/*
 * server
 *
 * <br/>https://ncloud.apigw.ntruss.com/server/v2
 *
 * API version: 2018-07-05T07:55:47Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

type Region struct {

RegionNo *string `json:"regionNo,omitempty"`

RegionCode *string `json:"regionCode,omitempty"`

RegionName *string `json:"regionName,omitempty"`
}
