/*
 * vpostgresql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vpostgresql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vpostgresql

type CloudPostgresqlBackupDetail struct {

	// 백업파일이름
FileName *string `json:"fileName,omitempty"`

	// 백업시작시간
StartTime *string `json:"startTime,omitempty"`

	// 백업종료시간
EndTime *string `json:"endTime,omitempty"`

	// 백업사이즈
BackupSize *int64 `json:"backupSize,omitempty"`

	// 데이터스토리지사이즈
DataStorageSize *int64 `json:"dataStorageSize,omitempty"`

	// ArchivedWalFile사이즈
ArchivedWalFileSize *int64 `json:"archivedWalFileSize,omitempty"`
}
