/*
 * autoscaling
 *
 * <br/>https://ncloud.apigw.ntruss.com/autoscaling/v2
 *
 * API version: 2018-06-21T02:22:22Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package autoscaling

type Zone struct {

	// 존(Zone)번호
ZoneNo *string `json:"zoneNo,omitempty"`

	// 존(Zone)명
ZoneName *string `json:"zoneName,omitempty"`

	// 존(Zone)설명
ZoneDescription *string `json:"zoneDescription,omitempty"`
}
