/*
 * vmongodb
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmongodb/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmongodb

type CloudMongoDbInstanceList struct {

	// CloudMongoDb인스턴스리스트
CloudMongoDbInstanceList []*CloudMongoDbInstance `json:"cloudMongoDbInstanceList,omitempty"`
}
