/*
 * vmongodb
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmongodb/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmongodb

type CloudMongoDbBackupList struct {

	// CloudMongoDb백업리스트
CloudMongoDbBackupList []*CloudMongoDbBackup `json:"cloudMongoDbBackupList,omitempty"`
}
