/*
 * server
 *
 * <br/>https://ncloud.apigw.ntruss.com/server/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

type AccessControlRuleParameter struct {

	// 서버인스턴스번호
ServerInstanceNo *string `json:"serverInstanceNo,omitempty"`

	// 커스텀IP
CustomIp *string `json:"customIp,omitempty"`

	// WriteAccess여부
WriteAccess *string `json:"writeAccess,omitempty"`
}
