/*
 * loadbalancer
 *
 * <br/>https://ncloud.apigw.ntruss.com/loadbalancer/v2
 *
 * API version: 2018-06-21T02:19:18Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package loadbalancer

type Region struct {

RegionNo *string `json:"regionNo,omitempty"`

RegionCode *string `json:"regionCode,omitempty"`

RegionName *string `json:"regionName,omitempty"`
}
