/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v1
 *
 * API version: 2022-04-21T09:07:51Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses

type MetricInfoResponseVo struct {
	Aggregation string `json:"aggregation,omitempty"`
	Dimensions *DimensionsVo `json:"dimensions,omitempty"`
	Dps [][]interface{} `json:"dps,omitempty"`
	GraphName string `json:"graphName,omitempty"`
	Interval string `json:"interval,omitempty"`
	Metric string `json:"metric,omitempty"`
	ProductName string `json:"productName,omitempty"`
}
