/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v1
 *
 * API version: 2022-04-21T09:07:51Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses

type OpenApiGetClusterInfoResponseVo struct {
	ClusterName            *string `json:"clusterName,omitempty"`
	ClusterStatus          *string `json:"clusterStatus,omitempty"`
	ApplicationVersionCode *string `json:"applicationVersionCode,omitempty"`
	LoginKeyName           *string `json:"loginKeyName,omitempty"`
	ServiceGroupInstanceNo *string `json:"serviceGroupInstanceNo,omitempty"`
	SoftwareProductCode    *string `json:"softwareProductCode,omitempty"`
	VpcNo                  *int32  `json:"vpcNo,omitempty"`

	DataNodeCount       *int32  `json:"dataNodeCount,omitempty"`
	DataNodeSubnetNo    *int32  `json:"dataNodeSubnetNo,omitempty"`
	DataNodeProductCode *string `json:"dataNodeProductCode,omitempty"`

	ManagerNodeCount       *int32  `json:"managerNodeCount,omitempty"`
	ManagerNodeSubnetNo    *int32  `json:"managerNodeSubnetNo,omitempty"`
	ManagerNodeProductCode *string `json:"managerNodeProductCode,omitempty"`

	MasterNodeCount       *int32  `json:"masterNodeCount,omitempty"`
	MasterNodeSubnetNo    *int32  `json:"masterNodeSubnetNo,omitempty"`
	MasterNodeProductCode *string `json:"masterNodeProductCode,omitempty"`
}
