/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type AssignSecondaryIpsRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// 네트워크인터페이스번호
NetworkInterfaceNo *string `json:"networkInterfaceNo"`

	// 보조IP리스트
SecondaryIpList []*string `json:"secondaryIpList,omitempty"`

	// 보조IP자동할당개수
SecondaryIpCount *int32 `json:"secondaryIpCount,omitempty"`

	// 명시적재할당허용여부
AllowReassign *bool `json:"allowReassign,omitempty"`
}
