/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type BlockStorage struct {

	// 스토리지 순서
Order *int32 `json:"order,omitempty"`

	// 스토리지 스냅샷 인스턴스 번호
SnapshotInstanceNo *string `json:"snapshotInstanceNo,omitempty"`

	// 스토리지 크기(GB)
BlockStorageSize *int32 `json:"blockStorageSize,omitempty"`

	// 스토리지 타입
BlockStorageVolumeTypeCode *string `json:"blockStorageVolumeTypeCode,omitempty"`

	// 신규 스토리지 생성 여부
EmptyBlockStorage *bool `json:"emptyBlockStorage,omitempty"`

	// 기존 스토이지 삭제 여부
NoBlockStorage *bool `json:"noBlockStorage,omitempty"`
}
