/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type CreateLoginKeyRequest struct {
	// Region Code : Ex) KR, JPN, SGN
	RegionCode 	*string `json:"regionCode,omitempty"`
	
	// 키 이름
	KeyName 	*string `json:"keyName,omitempty"`
}
// createLoginKey API Ref) https://api.ncloud-docs.com/docs/compute-vserver-server-loginkey-createloginkey
