/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type ServerSpec struct {

	// 서버스펙코드
	ServerSpecCode *string `json:"serverSpecCode,omitempty"`

	// 세대코드
	GenerationCode *string `json:"generationCode,omitempty"`

	// CPU개수
	CpuCount *int32 `json:"cpuCount,omitempty"`

	// 메모리사이즈
	MemorySize *int64 `json:"memorySize,omitempty"`

	// 하이퍼바이저유형
	HypervisorType *CommonCode `json:"hypervisorType,omitempty"`

	// CPU아키텍처유형
	CpuArchitectureType *CommonCode `json:"cpuArchitectureType,omitempty"`

	// 할당가능한스토리지최대개수
	BlockStorageMaxCount *int32 `json:"blockStorageMaxCount,omitempty"`

	// 스토리지최대IOPS
	BlockStorageMaxIops *int32 `json:"blockStorageMaxIops,omitempty"`

	// 스토리지최대부하처리성능
	BlockStorageMaxThroughput *int32 `json:"blockStorageMaxThroughput,omitempty"`

	// 네트워크성능
	NetworkPerformance *int64 `json:"networkPerformance,omitempty"`

	// 할당가능한네트워크인터페이스최대개수
	NetworkInterfaceMaxCount *int32 `json:"networkInterfaceMaxCount,omitempty"`

	// 서버상품코드
	ServerProductCode *string `json:"serverProductCode,omitempty"`

	// 서버스펙설명
	ServerSpecDescription *string `json:"serverSpecDescription,omitempty"`

	// GPU개수
	GpuCount *int32 `json:"gpuCount,omitempty"`
}
