/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type AllowedClusterInfo struct {
	ApplicationVersion string `json:"applicationVersion,omitempty"`
	BrokerNodeAccessControlGroupName string `json:"brokerNodeAccessControlGroupName,omitempty"`
	BrokerNodeAccessControlGroupSequence int32 `json:"brokerNodeAccessControlGroupSequence,omitempty"`
	BrokerNodeCount int32 `json:"brokerNodeCount,omitempty"`
	BrokerNodeProductName string `json:"brokerNodeProductName,omitempty"`
	BrokerNodeSubnetName string `json:"brokerNodeSubnetName,omitempty"`
	BrokerNodeSubnetNo int32 `json:"brokerNodeSubnetNo,omitempty"`
	BrokerNodeType string `json:"brokerNodeType,omitempty"`
	BrokerStorageVolumeSize int64 `json:"brokerStorageVolumeSize,omitempty"`
	ClusterName string `json:"clusterName,omitempty"`
	ClusterPublicDomain string `json:"clusterPublicDomain,omitempty"`
	CmakPort int32 `json:"cmakPort,omitempty"`
	CmakVersion string `json:"cmakVersion,omitempty"`
	CreateDate string `json:"createDate,omitempty"`
	IsUsePublicDomain bool `json:"isUsePublicDomain,omitempty"`
	KafkaBrokerPort int32 `json:"kafkaBrokerPort,omitempty"`
	KafkaBrokerTlsPort int32 `json:"kafkaBrokerTlsPort,omitempty"`
	KafkaManagerUserName string `json:"kafkaManagerUserName,omitempty"`
	KafkaVersion string `json:"kafkaVersion,omitempty"`
	ManagerNodeAccessControlGroupName string `json:"managerNodeAccessControlGroupName,omitempty"`
	ManagerNodeAccessControlGroupSequence int32 `json:"managerNodeAccessControlGroupSequence,omitempty"`
	ManagerNodeCount int32 `json:"managerNodeCount,omitempty"`
	ManagerNodeSubnetName string `json:"managerNodeSubnetName,omitempty"`
	ManagerNodeSubnetNo int32 `json:"managerNodeSubnetNo,omitempty"`
	ManagerNodeType string `json:"managerNodeType,omitempty"`
	MemberNo string `json:"memberNo,omitempty"`
	// serverStatus (creating[blue], changing[yelllow], running[green], error[red], deleting[gray], return[gray])
	ServerStatus string `json:"serverStatus"`
	ServiceGroupInstanceNo string `json:"serviceGroupInstanceNo,omitempty"`
	SoftwareProductName string `json:"softwareProductName,omitempty"`
	VpcName string `json:"vpcName,omitempty"`
	VpcNo int32 `json:"vpcNo,omitempty"`
	ZookeeperPort int32 `json:"zookeeperPort,omitempty"`
}
