/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type CreateCluster struct {
	ClusterName string `json:"clusterName"`
	KafkaVersionCode string `json:"kafkaVersionCode"`
	KafkaManagerUserName string `json:"kafkaManagerUserName"`
	KafkaManagerUserPassword string `json:"kafkaManagerUserPassword"`
	SoftwareProductCode string `json:"softwareProductCode"`
	VpcNo int32 `json:"vpcNo"`
	ManagerNodeProductCode string `json:"managerNodeProductCode"`
	ManagerNodeSubnetNo int32 `json:"managerNodeSubnetNo"`
	BrokerNodeProductCode string `json:"brokerNodeProductCode,omitempty"`
	BrokerNodeCount int32 `json:"brokerNodeCount"`
	BrokerNodeSubnetNo int32 `json:"brokerNodeSubnetNo"`
	BrokerNodeStorageSize int32 `json:"brokerNodeStorageSize"`
}
