/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type ErrorVo struct {
	Code string `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
	StackTrace string `json:"stackTrace,omitempty"`
}
