/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type GetBrokerNodeListsResponseVo struct {
	BrokerNodeList string `json:"brokerNodeList,omitempty"`
	BrokerTlsNodeList string `json:"brokerTlsNodeList,omitempty"`
	LocalDnsList string `json:"localDnsList,omitempty"`
	LocalDnsTlsList string `json:"localDnsTlsList,omitempty"`
	PublicEndpointBrokerNodeList string `json:"publicEndpointBrokerNodeList,omitempty"`
	PublicEndpointBrokerNodeListenerPortList string `json:"publicEndpointBrokerNodeListenerPortList,omitempty"`
	PublicEndpointBrokerTlsNodeList string `json:"publicEndpointBrokerTlsNodeList,omitempty"`
	PublicEndpointBrokerTlsNodeListenerPortList string `json:"publicEndpointBrokerTlsNodeListenerPortList,omitempty"`
	ZookeeperList string `json:"zookeeperList,omitempty"`
}
