/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type OpenApiGetComputeInstanceListResponseDetailVo struct {
	ComputeInstanceNo int32 `json:"computeInstanceNo,omitempty"`
	ComputeInstanceProductCode string `json:"computeInstanceProductCode,omitempty"`
	ComputeInstanceStatus string `json:"computeInstanceStatus,omitempty"`
	CpuCount int32 `json:"cpuCount,omitempty"`
	CreatedYmdt *DateTimeVo `json:"createdYmdt,omitempty"`
	HostName string `json:"hostName,omitempty"`
	MacAddress string `json:"macAddress,omitempty"`
	MemorySize int64 `json:"memorySize,omitempty"`
	NodeRoleCode string `json:"nodeRoleCode,omitempty"`
	OperationYmdt *DateTimeVo `json:"operationYmdt,omitempty"`
	OsInfo string `json:"osInfo,omitempty"`
	PrivateIp string `json:"privateIp,omitempty"`
	RegionCode string `json:"regionCode,omitempty"`
	RegionName string `json:"regionName,omitempty"`
	RegionNo string `json:"regionNo,omitempty"`
	SelfManaged bool `json:"selfManaged,omitempty"`
	ServiceGroupInstanceNo int32 `json:"serviceGroupInstanceNo,omitempty"`
	SubnetName string `json:"subnetName,omitempty"`
	SubnetNo int32 `json:"subnetNo,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	VpcName string `json:"vpcName,omitempty"`
	VpcNo int32 `json:"vpcNo,omitempty"`
	ZoneName string `json:"zoneName,omitempty"`
	ZoneNo int32 `json:"zoneNo,omitempty"`
}
