/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type OpenApiHwProductVo struct {
	CpuCount string `json:"cpuCount,omitempty"`
	DiskType2Code string `json:"diskType2Code,omitempty"`
	InfraResourceTypeCode string `json:"infraResourceTypeCode,omitempty"`
	MemorySize string `json:"memorySize,omitempty"`
	ProductCode string `json:"productCode,omitempty"`
	ProductEnglishDesc string `json:"productEnglishDesc,omitempty"`
	ProductName string `json:"productName,omitempty"`
	ProductType2Code string `json:"productType2Code,omitempty"`
}
