/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type OpenApiGetClusterInfoResponseVo struct {
	BrokerNodeCount          int32  `json:"brokerNodeCount,omitempty"`
	BrokerNodeProductCode    string `json:"brokerNodeProductCode,omitempty"`
	BrokerNodeStorageSize    int64  `json:"brokerNodeStorageSize,omitempty"`
	BrokerNodeSubnetNo       int32  `json:"brokerNodeSubnetNo,omitempty"`
	ClusterName              string `json:"clusterName,omitempty"`
	ConfigGroupNo            int32  `json:"configGroupNo,omitempty"`
	KafkaManagerUserName     string `json:"kafkaManagerUserName,omitempty"`
	KafkaManagerUserPassword string `json:"kafkaManagerUserPassword,omitempty"`
	KafkaVersionCode         string `json:"kafkaVersionCode,omitempty"`
	ManagerNodeProductCode   string `json:"managerNodeProductCode,omitempty"`
	ManagerNodeSubnetNo      int32  `json:"managerNodeSubnetNo,omitempty"`
	SoftwareProductCode      string `json:"softwareProductCode,omitempty"`
	Status                   string `json:"status,omitempty"`
	VpcNo                    int32  `json:"vpcNo,omitempty"`
}
