/*
 * api
 *
 * Cloud Data Streaming Service - Open API<br/>https://clouddatastreamingservice.beta-apigw.ntruss.com/api/v1
 *
 * API version: 2022-12-06T13:50:42Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type ProductListForCreation struct {
	BaseBlockStorageProductCode string `json:"baseBlockStorageProductCode,omitempty"`
	CpuCount                    string `json:"cpuCount,omitempty"`
	DiskType2Code               string `json:"diskType2Code,omitempty"`
	InfraResourceDetailTypeCode string `json:"infraResourceDetailTypeCode,omitempty"`
	InfraResourceTypeCode       string `json:"infraResourceTypeCode,omitempty"`
	IsChangeSpec                bool   `json:"isChangeSpec,omitempty"`
	IsSelected                  bool   `json:"isSelected,omitempty"`
	MemorySize                  int64  `json:"memorySize,omitempty"`
	ProductCode                 string `json:"productCode,omitempty"`
	ProductDesc                 string `json:"productDesc,omitempty"`
	ProductEnglishDesc          string `json:"productEnglishDesc,omitempty"`
	ProductEnglishName          string `json:"productEnglishName,omitempty"`
	ProductJapaneseDesc         string `json:"productJapaneseDesc,omitempty"`
	ProductJapaneseName         string `json:"productJapaneseName,omitempty"`
	ProductKoreanDesc           string `json:"productKoreanDesc,omitempty"`
	ProductKoreanName           string `json:"productKoreanName,omitempty"`
	ProductName                 string `json:"productName,omitempty"`
	ProductType2Code            string `json:"productType2Code,omitempty"`
}
