/*
 * sourcepipeline
 *
 * <br/>https://sourcepipeline.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcepipeline

type DeleteProjectResponse struct {
	Result *bool `json:"result,omitempty"`
}
