/*
 * sourcepipeline
 *
 * <br/>https://sourcepipeline.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcepipeline

type GetProjectDetailResponse struct {
	Id *int32 `json:"id,omitempty"`

	Name *string `json:"name,omitempty"`

	Description *string `json:"description,omitempty"`

	Tasks []*GetProjectDetailResponseTasks `json:"tasks,omitempty"`

	Trigger *GetProjectTrigger `json:"trigger,omitempty"`
}
