/*
 * sourcepipeline
 *
 * <br/>https://sourcepipeline.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcepipeline

type GetHistoryDetailResponseTasks struct {
	Id *int32 `json:"id,omitempty"`

	Name *string `json:"name,omitempty"`

	Type_ *string `json:"type,omitempty"`

	Config *GetHistoryDetailResponseConfig `json:"config,omitempty"`

	LinkedTasks []*string `json:"linkedTasks,omitempty"`

	Status *string `json:"status,omitempty"`

	ResultId *string `json:"resultId,omitempty"`
}
