/*
 * vsourcepipeline
 *
 * <br/>https://vpcsourcepipeline.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcepipeline

type GetProjectDetailResponseConfigTarget struct {
	Type_ *string `json:"type,omitempty"`

	Info *GetProjectDetailResponseConfigTargetInfo `json:"info,omitempty"`
}
