/*
 * vsourcepipeline
 *
 * <br/>https://vpcsourcepipeline.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcepipeline

type GetScRepositoryResposne struct {
	RepositoryList []*GetScBranchResponseBranchList `json:"repositoryList,omitempty"`
}
