/*
 * vsourcepipeline
 *
 * <br/>https://vpcsourcepipeline.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vsourcepipeline

type GetProjectTrigger struct {
	Repository []*GetRepositoryTrigger `json:"repository,omitempty"`

	Schedule []*GetScheduleTrigger `json:"schedule,omitempty"`

	SourcePipeline []*GetPipelineTrigger `json:"sourcepipeline,omitempty"`
}
