/*
 * api
 *
 * <br/>https://sourcecommit.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcecommit

type CreateRepository struct {
	Name *string `json:"name"`

	Description *string `json:"description,omitempty"`

	Linked *CreateRepositoryLinked `json:"linked,omitempty"`
}
