/*
 * clouddb
 *
 * Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package clouddb

type DeleteCloudDbServerInstanceRequest struct {

	// CloudDB서버인스턴스번호
CloudDBServerInstanceNo *string `json:"cloudDBServerInstanceNo"`
}
