/*
 * clouddb
 *
 * Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package clouddb

type FlushCloudDbInstanceRequest struct {

	// CloudDB인스턴스번호
CloudDBInstanceNo *string `json:"cloudDBInstanceNo"`
}
