/*
 * sourcebuild
 *
 * <br/>https://sourcebuild.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcebuild

type ChangeProject struct {
	Description *string `json:"description,omitempty"`

	Source *ProjectSource `json:"source,omitempty"`

	Env *ProjectEnv `json:"env,omitempty"`

	Cmd *ProjectCmd `json:"cmd,omitempty"`

	Artifact *ProjectArtifact `json:"artifact,omitempty"`

	Cache *ProjectCache `json:"cache,omitempty"`

	Linked *ProjectLinked `json:"linked,omitempty"`
}
