/*
 * sourcebuild
 *
 * <br/>https://sourcebuild.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcebuild

// os id
type EnvPlatformConfigRequestOs struct {
	Id *int32 `json:"id,omitempty"`
}
