/*
 * sourcebuild
 *
 * <br/>https://sourcebuild.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcebuild

type GetProjectListResponse struct {
	Total *int32 `json:"total,omitempty"`

	Project []*GetProjectListResponseProject `json:"project,omitempty"`
}
