/*
 * sourcebuild
 *
 * <br/>https://sourcebuild.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcebuild

type GetScBranchResponse struct {
	Default_ *string `json:"default,omitempty"`

	Branch []*string `json:"branch,omitempty"`
}
