/*
 * sourcebuild
 *
 * <br/>https://sourcebuild.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcebuild

type GetRuntimeEnvResponse struct {
	Runtime []*GetDockerEnvResponseDocker `json:"runtime,omitempty"`
}
