/*
 * api
 *
* <br/>https://sourcebuild.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcebuild

type GetProjectDetailResponseEnvCompute struct {
	Id *int32 `json:"id,omitempty"`

	Cpu *int32 `json:"cpu,omitempty"`

	Mem *int32 `json:"mem,omitempty"`
}
