/*
 * sourcebuild
 *
 * <br/>https://sourcebuild.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcebuild

type ProjectEnv struct {
	Compute *ProjectEnvCompute `json:"compute"`

	Platform *ProjectEnvPlatform `json:"platform"`

	Docker *ProjectEnvDocker `json:"docker,omitempty"`

	Timeout *int32 `json:"timeout,omitempty"`

	EnvVars []*ProjectEnvEnvVars `json:"envVars,omitempty"`
}
