/*
 * sourcebuild
 *
 * <br/>https://sourcebuild.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcebuild

type ProjectCache struct {
	Use *bool `json:"use,omitempty"`

	Registry *string `json:"registry,omitempty"`

	Image *string `json:"image,omitempty"`

	Tag *string `json:"tag,omitempty"`

	Latest *bool `json:"latest,omitempty"`
}
