/*
 * vpc
 *
 * VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vpc

type GetNatGatewayInstanceListRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// ZONE코드
ZoneCode *string `json:"zoneCode,omitempty"`

	// NATGateway인스턴스번호리스트
NatGatewayInstanceNoList []*string `json:"natGatewayInstanceNoList,omitempty"`

	// 공인IP주소
PublicIp *string `json:"publicIp,omitempty"`

	// VPC이름
VpcName *string `json:"vpcName,omitempty"`

	// natGatewayName
NatGatewayName *string `json:"natGatewayName,omitempty"`

	// NATGateway인스턴스상태코드
NatGatewayInstanceStatusCode *string `json:"natGatewayInstanceStatusCode,omitempty"`

	// NATGateway유형 (PRVT / PBLIP)
NatGatewayTypeCode *string `json:"natGatewayTypeCode,omitempty"`

	// Subnet번호
SubnetNo *string `json:"subnetNo,omitempty"`

	// Subnet이름
SubnetName *string `json:"subnetName,omitempty"`

	// 사설IP주소
PrivateIp *string `json:"privateIp,omitempty"`

	// 페이지번호
PageNo *int32 `json:"pageNo,omitempty"`

	// 페이지사이즈
PageSize *int32 `json:"pageSize,omitempty"`
}
