/*
 * vpc
 *
 * VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vpc

type GetNetworkAclDenyAllowGroupListRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// VPC번호
VpcNo *string `json:"vpcNo,omitempty"`

	// 네트워크ACL허용차단그룹이름
NetworkAclDenyAllowGroupName *string `json:"networkAclDenyAllowGroupName,omitempty"`

	// 네트워크ACL허용차단그룹상태코드
NetworkAclDenyAllowGroupStatusCode *string `json:"networkAclDenyAllowGroupStatusCode,omitempty"`

	// 네트워크ACLRule적용여부
IsApplied *bool `json:"isApplied,omitempty"`

	// 네트워크ACL허용차단그룹번호리스트
NetworkAclDenyAllowGroupNoList []*string `json:"networkAclDenyAllowGroupNoList,omitempty"`

	// 페이지번호
PageNo *int32 `json:"pageNo,omitempty"`

	// 페이지사이즈
PageSize *int32 `json:"pageSize,omitempty"`
}
