/*
 * vmysql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmysql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmysql

type CloudMysqlUser struct {

	// DBUserID
	UserName *string `json:"userName,omitempty"`

	// 접근IP
	HostIp *string `json:"hostIp,omitempty"`

	// DB권한
	Authority *string `json:"authority,omitempty"`
}
