/*
 * vmysql
 *
 * <br/>https://ncloud.apigw.ntruss.com/vmysql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmysql

type GetDbServerLogListRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// 데이터베이스서버로그파일타입
LogType *string `json:"logType"`

	// CloudMysql서버인스턴스번호
CloudMysqlServerInstanceNo *string `json:"cloudMysqlServerInstanceNo"`
}
