/*
 * monitoring
 *
 * <br/>https://ncloud.apigw.ntruss.com/monitoring/v2
 *
 * API version: 2020-05-13T08:22:44Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package monitoring

type Metric struct {

InstanceNo *string `json:"instanceNo,omitempty"`

MetricName *string `json:"metricName,omitempty"`
}
